# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-05 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=100, null=True, verbose_name='SKU')),
                ('asin', models.CharField(blank=True, max_length=100, null=True, verbose_name='ASIN')),
                ('bb_status', models.BooleanField(default=False, verbose_name='BB Status')),
                ('bb_owner', models.CharField(blank=True, max_length=100, null=True, verbose_name='Who Has BB')),
                ('our_min_price', models.FloatField(blank=True, null=True, verbose_name='Our Min Price')),
                ('bb_price', models.FloatField(blank=True, null=True, verbose_name='BuyBox Price')),
                ('appeagle_strategy', models.CharField(blank=True, choices=[('38344', 'AN No Tax BB (10%)'), ('38345', 'AN No Tax No BB (10%)'), ('38346', 'AN OS BB (10%)'), ('38347', 'AN OS No BB (10%)'), ('38342', 'AN Tax BB (10%)'), ('38343', 'AN Tax No BB (10%)'), ('38449', 'BB (5% No Tax)'), ('38450', 'BB (5% Tax)'), ('38435', 'CM BB'), ('38436', 'CM No BB'), ('23303', 'Managed Items Strategy (All)'), ('38451', 'No BB (5% No Tax)'), ('38452', 'No BB (5% Tax)'), ('38567', 'OS BB (5%)'), ('38568', 'OS No BB (5%)')], max_length=10, null=True, verbose_name='Appeagle Strategy')),
                ('prime_az', models.BooleanField(default=False, verbose_name='Prime/AZ')),
                ('num_orders', models.IntegerField(blank=True, default=0, null=True, verbose_name='No. Of Orders w/in 30 Days ')),
                ('prev_bb_price', models.FloatField(blank=True, null=True, verbose_name='BB Price Previously')),
            ],
        ),
        migrations.CreateModel(
            name='RunTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_at', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='run_at',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='general.RunTime', verbose_name='Run Time'),
        ),
    ]
