# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-05 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Title'),
        ),
    ]
